// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: createFeed.sql

package database

import (
	"context"
)

const createFeed = `-- name: CreateFeed :exec
CREATE TABLE feeds (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name TEXT,
    url TEXT NOT NULL,
    user_id TEXT NOT NULL,
    CONSTRAINT fk_user_id
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
)
`

func (q *Queries) CreateFeed(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createFeed)
	return err
}
