// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: findUnfollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const findToUnfollow = `-- name: FindToUnfollow :exec
DELETE
FROM feed_follows
WHERE feed_follows.user_id = $1 AND feed_id IN (
    SELECT id
    FROM feeds
    WHERE url = $2
)
`

type FindToUnfollowParams struct {
	UserID uuid.UUID
	Url    string
}

func (q *Queries) FindToUnfollow(ctx context.Context, arg FindToUnfollowParams) error {
	_, err := q.db.ExecContext(ctx, findToUnfollow, arg.UserID, arg.Url)
	return err
}
