// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getuser.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT name 
FROM users
`

func (q *Queries) GetUser(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getUser)
	var name string
	err := row.Scan(&name)
	return name, err
}
