// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: MarkFeedFetched.sql

package database

import (
	"context"
)

const markFeedFetched = `-- name: MarkFeedFetched :exec
UPDATE feeds
SET last_fetched_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkFeedFetched(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markFeedFetched, id)
	return err
}
